using OrigamiPlatform.Domain.Enums;

namespace OrigamiPlatform.Domain.Entities;

// FT-34: one row per calendar day (GMT+7). CreatedByUserId is null when the system auto-picked
// the tutorial (safety net); otherwise it's the Admin/Manager who scheduled it.
public class DailyChallenge
{
    public Guid Id { get; set; }
    public DateOnly ChallengeDate { get; set; }
    public Guid TutorialId { get; set; }
    public Guid? CreatedByUserId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DailyChallengeStatus Status { get; set; }
    public DateTime? ResultCalculatedAt { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public Tutorial Tutorial { get; set; } = null!;
    public User? CreatedByUser { get; set; }
    public ICollection<DailyChallengeSubmission> Submissions { get; set; } = new List<DailyChallengeSubmission>();
}
