using OrigamiPlatform.Domain.Enums;

namespace OrigamiPlatform.Domain.Entities;

// Thử thách tuần: một hàng cho mỗi Chủ Nhật (GMT+7) — mirror DailyChallenge (FT-34) nhưng
// ChallengeDate luôn là Chủ Nhật và độ khó tutorial luôn là Advanced. CreatedByUserId là null
// khi hệ thống tự chọn (safety net); ngược lại là Admin/Manager đã đặt lịch.
public class WeeklyChallenge
{
    public Guid Id { get; set; }
    public DateOnly ChallengeDate { get; set; }
    public Guid TutorialId { get; set; }
    public Guid? CreatedByUserId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DailyChallengeStatus Status { get; set; }
    public DateTime? ResultCalculatedAt { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public Tutorial Tutorial { get; set; } = null!;
    public User? CreatedByUser { get; set; }
    public ICollection<WeeklyChallengeSubmission> Submissions { get; set; } = new List<WeeklyChallengeSubmission>();
}
