namespace OrigamiPlatform.Application.DTOs.Tutorials;

public record TutorialDetailDto(
    Guid Id,
    string Title,
    string Slug,
    string Description,
    string? CoverImageUrl,
    string Type,
    string Difficulty,
    int CategoryId,
    string CategoryName,
    AuthorDto Author,
    IEnumerable<TutorialStepDto> Steps,
    DateTime PublishedAt,
    bool IsVipLocked,
    int LikeCount,
    int WishlistCount,
    bool IsLikedByCurrentUser,
    bool IsWishlistedByCurrentUser,
    string? MetaTitle = null,
    string? MetaDescription = null,
    string? Tags = null,
    TutorialRatingSummaryDto? RatingSummary = null,
    bool HasAchievement = false,
    bool HasRated = false,
    int CompletedStepCount = 0,
    int TotalStepCount = 0,
    int ProgressPercent = 0,
    int CompletedCount = 0
);
