using OrigamiPlatform.Application.Common;
using OrigamiPlatform.Application.Interfaces;
using OrigamiPlatform.Domain.Constants;
using OrigamiPlatform.Domain.Entities;
using OrigamiPlatform.Domain.Enums;

namespace OrigamiPlatform.Application.Commands.DailyChallenge;

// FT-34: idempotent — safe to call repeatedly for the same day. If Admin/Manager already
// scheduled today's challenge, promotes it to Active; otherwise auto-picks a tutorial as a
// safety net so a day is never left without a challenge.
public class ActivateDailyChallengeHandler
{
    // Ngày thường: 50% Beginner / 35% Intermediate / 15% Advanced.
    private const double BeginnerWeight = 0.50;
    private const double IntermediateWeight = 0.85; // cumulative

    private readonly IDailyChallengeRepository _challenges;
    private readonly HatGapAwardService _hatGap;
    private readonly BadgeAwardService _badges;
    private readonly INotificationService _notifications;

    public ActivateDailyChallengeHandler(
        IDailyChallengeRepository challenges,
        HatGapAwardService hatGap,
        BadgeAwardService badges,
        INotificationService notifications)
        => (_challenges, _hatGap, _badges, _notifications) = (challenges, hatGap, badges, notifications);

    public async Task HandleAsync(ActivateDailyChallengeCommand command, CancellationToken ct = default)
    {
        var today = GetTodayGmt7();
        var existing = await _challenges.GetByDateAsync(today, ct);

        if (existing is not null)
        {
            if (existing.Status != DailyChallengeStatus.Scheduled)
                return; // already Active or Closed — idempotent no-op

            existing.Status = DailyChallengeStatus.Active;
            existing.UpdatedAt = DateTime.UtcNow;
            await _challenges.UpdateAsync(existing, ct);

            await NotifyAndRewardAuthorAsync(existing.Id, existing.Tutorial, ct);
            return;
        }

        var tutorial = await PickTutorialAsync(today, ct);
        if (tutorial is null)
            return; // no eligible Published tutorial exists at all yet — nothing to do; caller logs this

        var created = new OrigamiPlatform.Domain.Entities.DailyChallenge
        {
            Id = Guid.NewGuid(),
            ChallengeDate = today,
            TutorialId = tutorial.Id,
            CreatedByUserId = null,
            IsAutoGenerated = true,
            Status = DailyChallengeStatus.Active,
            CreatedAt = DateTime.UtcNow
        };
        await _challenges.AddAsync(created, ct);

        await NotifyAndRewardAuthorAsync(created.Id, tutorial, ct);
    }

    private async Task NotifyAndRewardAuthorAsync(Guid challengeId, Tutorial tutorial, CancellationToken ct)
    {
        try
        {
            await _hatGap.AwardAsync(
                tutorial.AuthorId, HatGapEconomy.DailyChallengeAuthorSelectedReward, HatGapTransactionType.Earn,
                "DailyChallengeAuthorSelected", ct);

            await _notifications.NotifyUserAsync(
                userId: tutorial.AuthorId,
                type: NotificationType.TutorialSelectedAsChallenge,
                message: $"Hướng dẫn \"{tutorial.Title}\" của bạn đã trở thành Thử thách ngày hôm nay! +{HatGapEconomy.DailyChallengeAuthorSelectedReward} Hạt Gấp 🎉",
                entityType: nameof(OrigamiPlatform.Domain.Entities.DailyChallenge),
                entityId: challengeId,
                ct: ct);

            await _badges.TryAwardAsync(tutorial.AuthorId, "CHALLENGE_AUTHOR_SELECTED", contextRefId: challengeId, ct: ct);

            var authorSelectedCount = await _challenges.CountByTutorialAuthorAsync(tutorial.AuthorId, ct);
            if (authorSelectedCount >= 5)
                await _badges.TryAwardAsync(tutorial.AuthorId, "CHALLENGE_AUTHOR_5X", contextRefId: challengeId, ct: ct);
        }
        catch
        {
            // author reward/notify failure must not block challenge activation
        }
    }

    // BR-34 fallback chain: relax difficulty filter, then relax the 30-day "recently used"
    // exclusion, so a day is never left without a challenge as long as any Published tutorial exists.
    private async Task<Tutorial?> PickTutorialAsync(DateOnly today, CancellationToken ct)
    {
        var excludeIds = await _challenges.GetRecentlyUsedTutorialIdsAsync(today.AddDays(-30), ct);
        var isFreeFoldDay = today.DayOfWeek == DayOfWeek.Sunday;
        var difficulty = isFreeFoldDay ? TutorialDifficulty.Beginner : PickWeightedDifficulty();

        var candidates = await _challenges.GetEligibleCandidatesAsync(excludeIds, difficulty, ct);
        if (candidates.Count == 0)
            candidates = await _challenges.GetEligibleCandidatesAsync(excludeIds, null, ct);
        if (candidates.Count == 0)
            candidates = await _challenges.GetEligibleCandidatesAsync(new HashSet<Guid>(), null, ct);

        return candidates.Count == 0 ? null : PickWeightedRandom(candidates);
    }

    private static TutorialDifficulty PickWeightedDifficulty()
    {
        var roll = Random.Shared.NextDouble();
        return roll switch
        {
            < BeginnerWeight => TutorialDifficulty.Beginner,
            < IntermediateWeight => TutorialDifficulty.Intermediate,
            _ => TutorialDifficulty.Advanced
        };
    }

    // Weighted random by (1 + AchievementCount) — favors proven/popular tutorials without
    // making the same handful always win.
    private static Tutorial PickWeightedRandom(List<(Tutorial Tutorial, int AchievementCount)> candidates)
    {
        var weights = candidates.Select(c => 1 + c.AchievementCount).ToList();
        var totalWeight = weights.Sum();
        var roll = Random.Shared.Next(totalWeight);

        var cumulative = 0;
        for (var i = 0; i < candidates.Count; i++)
        {
            cumulative += weights[i];
            if (roll < cumulative)
                return candidates[i].Tutorial;
        }

        return candidates[^1].Tutorial;
    }

    private static DateOnly GetTodayGmt7() => DateOnly.FromDateTime(DateTime.UtcNow.AddHours(7));
}
