using OrigamiPlatform.Application.DTOs.DailyChallenge;
using OrigamiPlatform.Application.Interfaces;
using OrigamiPlatform.Domain.Entities;
using OrigamiPlatform.Domain.Enums;
using OrigamiPlatform.Domain.Exceptions;

namespace OrigamiPlatform.Application.Commands.DailyChallenge;

// FT-34: Admin/Manager schedules ahead of time — only ChallengeDate > today (tomorrow onward) is
// accepted, so a day that's already ongoing can never be edited mid-way. This always leaves the
// row as Scheduled (never Active directly). Activation (and the author reward/notify side effects
// that go with it) only ever happens through ActivateDailyChallengeHandler, either via the nightly
// DailyChallengeSchedulerService job or the admin "run now" endpoint for testing.
public class AdminScheduleDailyChallengeHandler
{
    private readonly IDailyChallengeRepository _challenges;
    private readonly ITutorialRepository _tutorials;

    public AdminScheduleDailyChallengeHandler(IDailyChallengeRepository challenges, ITutorialRepository tutorials)
        => (_challenges, _tutorials) = (challenges, tutorials);

    public async Task<DailyChallengeDto> HandleAsync(
        AdminScheduleDailyChallengeCommand command, CancellationToken ct = default)
    {
        var today = GetTodayGmt7();
        if (command.Request.ChallengeDate <= today)
            throw new DomainException("Chỉ có thể đặt lịch/sửa cho thử thách từ ngày mai trở đi. Thử thách của ngày hôm nay đang diễn ra nên không thể thay đổi giữa chừng.");

        var tutorial = await _tutorials.GetByIdWithStepsAsync(command.Request.TutorialId, ct)
            ?? throw new NotFoundException("Tutorial not found.");

        if (tutorial.Status != TutorialStatus.Published)
            throw new DomainException("Chỉ có thể chọn tutorial đã ở trạng thái Published.");

        var existing = await _challenges.GetByDateAsync(command.Request.ChallengeDate, ct);

        Guid challengeId;
        if (existing is null)
        {
            var challenge = new OrigamiPlatform.Domain.Entities.DailyChallenge
            {
                Id = Guid.NewGuid(),
                ChallengeDate = command.Request.ChallengeDate,
                TutorialId = tutorial.Id,
                CreatedByUserId = command.ActorId,
                IsAutoGenerated = false,
                Status = DailyChallengeStatus.Scheduled,
                CreatedAt = DateTime.UtcNow
            };
            await _challenges.AddAsync(challenge, ct);
            challengeId = challenge.Id;
        }
        else
        {
            if (existing.Status != DailyChallengeStatus.Scheduled)
                throw new DomainException("Không thể sửa lịch của ngày đã kích hoạt hoặc đã đóng.");

            existing.TutorialId = tutorial.Id;
            existing.CreatedByUserId = command.ActorId;
            existing.IsAutoGenerated = false;
            existing.UpdatedAt = DateTime.UtcNow;
            await _challenges.UpdateAsync(existing, ct);
            challengeId = existing.Id;
        }

        var saved = await _challenges.GetByIdAsync(challengeId, ct)
            ?? throw new NotFoundException("Daily challenge not found after save.");

        return saved.ToDto(submissionCount: 0, hasSubmittedToday: null, myChallengeStreak: null);
    }

    private static DateOnly GetTodayGmt7() => DateOnly.FromDateTime(DateTime.UtcNow.AddHours(7));
}
