using OrigamiPlatform.Application.DTOs.LearningPathModes;

namespace OrigamiPlatform.Application.Commands.LearningPathModes;

public record CreateLearningPathModeCommand(CreateLearningPathModeRequest Request);
