namespace OrigamiPlatform.Application.DTOs.WeeklyChallenge;

public record AdminWeeklyChallengeCalendarItemDto(
    Guid Id,
    DateOnly ChallengeDate,
    string Status,
    Guid TutorialId,
    string TutorialTitle,
    bool IsAutoGenerated,
    Guid? CreatedByUserId
);
