using OrigamiPlatform.Domain.Entities;

namespace OrigamiPlatform.Application.DTOs.WeeklyChallenge;

public static class WeeklyChallengeMapping
{
    public static WeeklyChallengeDto ToDto(
        this OrigamiPlatform.Domain.Entities.WeeklyChallenge challenge,
        int submissionCount,
        bool? hasSubmittedThisWeek,
        int? myChallengeStreak)
        => new(
            challenge.Id,
            challenge.ChallengeDate,
            challenge.Status.ToString(),
            challenge.TutorialId,
            challenge.Tutorial.Title,
            challenge.Tutorial.Slug,
            challenge.Tutorial.CoverImageUrl,
            challenge.Tutorial.Difficulty.ToString(),
            challenge.Tutorial.AuthorId,
            challenge.Tutorial.Author?.Profile?.DisplayName,
            challenge.IsAutoGenerated,
            submissionCount,
            hasSubmittedThisWeek,
            myChallengeStreak,
            challenge.CreatedAt);

    public static WeeklyChallengeSubmissionDto ToDto(
        this WeeklyChallengeSubmission submission, int likeCount, bool isLikedByCurrentUser)
        => new(
            submission.Id,
            submission.UserId,
            submission.User?.Profile?.DisplayName,
            submission.User?.Profile?.AvatarUrl,
            submission.PhotoUrl,
            submission.Note,
            likeCount,
            isLikedByCurrentUser,
            submission.FinalRank,
            submission.CreatedAt);

    public static AdminWeeklyChallengeCalendarItemDto ToAdminCalendarDto(this OrigamiPlatform.Domain.Entities.WeeklyChallenge challenge)
        => new(
            challenge.Id,
            challenge.ChallengeDate,
            challenge.Status.ToString(),
            challenge.TutorialId,
            challenge.Tutorial.Title,
            challenge.IsAutoGenerated,
            challenge.CreatedByUserId);
}
