namespace OrigamiPlatform.Application.DTOs.WeeklyChallenge;

public record WeeklyChallengeDto(
    Guid Id,
    DateOnly ChallengeDate,
    string Status,
    Guid TutorialId,
    string TutorialTitle,
    string TutorialSlug,
    string? TutorialCoverImageUrl,
    string TutorialDifficulty,
    Guid TutorialAuthorId,
    string? TutorialAuthorName,
    bool IsAutoGenerated,
    int SubmissionCount,
    bool? HasSubmittedThisWeek,
    int? MyChallengeStreak,
    DateTime CreatedAt
);
