namespace OrigamiPlatform.Application.DTOs.DailyChallenge;

public record AdminChallengeCalendarItemDto(
    Guid Id,
    DateOnly ChallengeDate,
    string Status,
    Guid TutorialId,
    string TutorialTitle,
    bool IsAutoGenerated,
    Guid? CreatedByUserId
);
