namespace OrigamiPlatform.Application.DTOs.DailyChallenge;

public record DailyChallengeDto(
    Guid Id,
    DateOnly ChallengeDate,
    string Status,
    Guid TutorialId,
    string TutorialTitle,
    string TutorialSlug,
    string? TutorialCoverImageUrl,
    string TutorialDifficulty,
    Guid TutorialAuthorId,
    string? TutorialAuthorName,
    bool IsAutoGenerated,
    int SubmissionCount,
    bool? HasSubmittedToday,
    int? MyChallengeStreak,
    DateTime CreatedAt
);
