using OrigamiPlatform.Domain.Entities;

namespace OrigamiPlatform.Application.DTOs.DailyChallenge;

public static class DailyChallengeMapping
{
    public static DailyChallengeDto ToDto(
        this OrigamiPlatform.Domain.Entities.DailyChallenge challenge,
        int submissionCount,
        bool? hasSubmittedToday,
        int? myChallengeStreak)
        => new(
            challenge.Id,
            challenge.ChallengeDate,
            challenge.Status.ToString(),
            challenge.TutorialId,
            challenge.Tutorial.Title,
            challenge.Tutorial.Slug,
            challenge.Tutorial.CoverImageUrl,
            challenge.Tutorial.Difficulty.ToString(),
            challenge.Tutorial.AuthorId,
            challenge.Tutorial.Author?.Profile?.DisplayName,
            challenge.IsAutoGenerated,
            submissionCount,
            hasSubmittedToday,
            myChallengeStreak,
            challenge.CreatedAt);

    public static DailyChallengeSubmissionDto ToDto(
        this DailyChallengeSubmission submission, int likeCount, bool isLikedByCurrentUser)
        => new(
            submission.Id,
            submission.UserId,
            submission.User?.Profile?.DisplayName,
            submission.User?.Profile?.AvatarUrl,
            submission.PhotoUrl,
            submission.Note,
            likeCount,
            isLikedByCurrentUser,
            submission.FinalRank,
            submission.CreatedAt);

    public static AdminChallengeCalendarItemDto ToAdminCalendarDto(this OrigamiPlatform.Domain.Entities.DailyChallenge challenge)
        => new(
            challenge.Id,
            challenge.ChallengeDate,
            challenge.Status.ToString(),
            challenge.TutorialId,
            challenge.Tutorial.Title,
            challenge.IsAutoGenerated,
            challenge.CreatedByUserId);
}
