using OrigamiPlatform.Application.Common;
using OrigamiPlatform.Application.Interfaces;
using OrigamiPlatform.Domain.Constants;
using OrigamiPlatform.Domain.Entities;
using OrigamiPlatform.Domain.Enums;

namespace OrigamiPlatform.Application.Commands.WeeklyChallenge;

// Idempotent — safe to call repeatedly. Chỉ mở vào Chủ Nhật (GMT+7); mọi ngày khác no-op ngay.
// Nếu Admin/Manager đã đặt lịch cho Chủ Nhật này, promote sang Active; nếu chưa, tự chọn 1
// tutorial Advanced làm safety net, mirror ActivateDailyChallengeHandler.
public class ActivateWeeklyChallengeHandler
{
    private readonly IWeeklyChallengeRepository _challenges;
    private readonly HatGapAwardService _hatGap;
    private readonly BadgeAwardService _badges;
    private readonly INotificationService _notifications;

    public ActivateWeeklyChallengeHandler(
        IWeeklyChallengeRepository challenges,
        HatGapAwardService hatGap,
        BadgeAwardService badges,
        INotificationService notifications)
        => (_challenges, _hatGap, _badges, _notifications) = (challenges, hatGap, badges, notifications);

    public async Task HandleAsync(ActivateWeeklyChallengeCommand command, CancellationToken ct = default)
    {
        var today = GetTodayGmt7();
        if (today.DayOfWeek != DayOfWeek.Sunday)
            return; // Thử thách tuần chỉ có thể mở vào Chủ Nhật

        var existing = await _challenges.GetByDateAsync(today, ct);

        if (existing is not null)
        {
            if (existing.Status != DailyChallengeStatus.Scheduled)
                return; // already Active or Closed — idempotent no-op

            existing.Status = DailyChallengeStatus.Active;
            existing.UpdatedAt = DateTime.UtcNow;
            await _challenges.UpdateAsync(existing, ct);

            await NotifyAndRewardAuthorAsync(existing.Id, existing.Tutorial, ct);
            return;
        }

        var tutorial = await PickTutorialAsync(today, ct);
        if (tutorial is null)
            return; // no eligible Published tutorial exists at all yet — nothing to do; caller logs this

        var created = new OrigamiPlatform.Domain.Entities.WeeklyChallenge
        {
            Id = Guid.NewGuid(),
            ChallengeDate = today,
            TutorialId = tutorial.Id,
            CreatedByUserId = null,
            IsAutoGenerated = true,
            Status = DailyChallengeStatus.Active,
            CreatedAt = DateTime.UtcNow
        };
        await _challenges.AddAsync(created, ct);

        await NotifyAndRewardAuthorAsync(created.Id, tutorial, ct);
    }

    private async Task NotifyAndRewardAuthorAsync(Guid challengeId, Tutorial tutorial, CancellationToken ct)
    {
        try
        {
            await _hatGap.AwardAsync(
                tutorial.AuthorId, HatGapEconomy.WeeklyChallengeAuthorSelectedReward, HatGapTransactionType.Earn,
                "WeeklyChallengeAuthorSelected", ct);

            await _notifications.NotifyUserAsync(
                userId: tutorial.AuthorId,
                type: NotificationType.TutorialSelectedAsChallenge,
                message: $"Hướng dẫn \"{tutorial.Title}\" của bạn đã trở thành Thử thách tuần tuần này! +{HatGapEconomy.WeeklyChallengeAuthorSelectedReward} Hạt Gấp 🎉",
                entityType: nameof(OrigamiPlatform.Domain.Entities.WeeklyChallenge),
                entityId: challengeId,
                ct: ct);

            await _badges.TryAwardAsync(tutorial.AuthorId, "CHALLENGE_AUTHOR_SELECTED", contextRefId: challengeId, ct: ct);

            var authorSelectedCount = await _challenges.CountByTutorialAuthorAsync(tutorial.AuthorId, ct);
            if (authorSelectedCount >= 5)
                await _badges.TryAwardAsync(tutorial.AuthorId, "CHALLENGE_AUTHOR_5X", contextRefId: challengeId, ct: ct);
        }
        catch
        {
            // author reward/notify failure must not block challenge activation
        }
    }

    // BR-34 fallback chain: relax difficulty filter, then relax the 30-day "recently used"
    // exclusion, so a Sunday is never left without a challenge as long as any Published tutorial exists.
    private async Task<Tutorial?> PickTutorialAsync(DateOnly today, CancellationToken ct)
    {
        var excludeIds = await _challenges.GetRecentlyUsedTutorialIdsAsync(today.AddDays(-30), ct);

        var candidates = await _challenges.GetEligibleCandidatesAsync(excludeIds, TutorialDifficulty.Advanced, ct);
        if (candidates.Count == 0)
            candidates = await _challenges.GetEligibleCandidatesAsync(excludeIds, null, ct);
        if (candidates.Count == 0)
            candidates = await _challenges.GetEligibleCandidatesAsync(new HashSet<Guid>(), null, ct);

        return candidates.Count == 0 ? null : PickWeightedRandom(candidates);
    }

    // Weighted random by (1 + AchievementCount) — favors proven/popular tutorials without
    // making the same handful always win.
    private static Tutorial PickWeightedRandom(List<(Tutorial Tutorial, int AchievementCount)> candidates)
    {
        var weights = candidates.Select(c => 1 + c.AchievementCount).ToList();
        var totalWeight = weights.Sum();
        var roll = Random.Shared.Next(totalWeight);

        var cumulative = 0;
        for (var i = 0; i < candidates.Count; i++)
        {
            cumulative += weights[i];
            if (roll < cumulative)
                return candidates[i].Tutorial;
        }

        return candidates[^1].Tutorial;
    }

    private static DateOnly GetTodayGmt7() => DateOnly.FromDateTime(DateTime.UtcNow.AddHours(7));
}
