using OrigamiPlatform.Application.DTOs.WeeklyChallenge;
using OrigamiPlatform.Application.Interfaces;
using OrigamiPlatform.Domain.Entities;
using OrigamiPlatform.Domain.Enums;
using OrigamiPlatform.Domain.Exceptions;

namespace OrigamiPlatform.Application.Commands.WeeklyChallenge;

// Admin/Manager đặt lịch trước — luôn để row ở trạng thái Scheduled (không bao giờ Active trực
// tiếp), kể cả khi ChallengeDate là Chủ Nhật hôm nay. Mirror AdminScheduleDailyChallengeHandler,
// thêm ràng buộc ChallengeDate bắt buộc phải là Chủ Nhật ("chỉ mở vào cuối tuần").
public class AdminScheduleWeeklyChallengeHandler
{
    private readonly IWeeklyChallengeRepository _challenges;
    private readonly ITutorialRepository _tutorials;

    public AdminScheduleWeeklyChallengeHandler(IWeeklyChallengeRepository challenges, ITutorialRepository tutorials)
        => (_challenges, _tutorials) = (challenges, tutorials);

    public async Task<WeeklyChallengeDto> HandleAsync(
        AdminScheduleWeeklyChallengeCommand command, CancellationToken ct = default)
    {
        var today = GetTodayGmt7();
        if (command.Request.ChallengeDate < today)
            throw new DomainException("Không thể đặt lịch cho ngày trong quá khứ.");

        if (command.Request.ChallengeDate.DayOfWeek != DayOfWeek.Sunday)
            throw new DomainException("Thử thách tuần chỉ có thể mở vào Chủ Nhật.");

        var tutorial = await _tutorials.GetByIdWithStepsAsync(command.Request.TutorialId, ct)
            ?? throw new NotFoundException("Tutorial not found.");

        if (tutorial.Status != TutorialStatus.Published)
            throw new DomainException("Chỉ có thể chọn tutorial đã ở trạng thái Published.");

        var existing = await _challenges.GetByDateAsync(command.Request.ChallengeDate, ct);

        Guid challengeId;
        if (existing is null)
        {
            var challenge = new OrigamiPlatform.Domain.Entities.WeeklyChallenge
            {
                Id = Guid.NewGuid(),
                ChallengeDate = command.Request.ChallengeDate,
                TutorialId = tutorial.Id,
                CreatedByUserId = command.ActorId,
                IsAutoGenerated = false,
                Status = DailyChallengeStatus.Scheduled,
                CreatedAt = DateTime.UtcNow
            };
            await _challenges.AddAsync(challenge, ct);
            challengeId = challenge.Id;
        }
        else
        {
            if (existing.Status != DailyChallengeStatus.Scheduled)
                throw new DomainException("Không thể sửa lịch của tuần đã kích hoạt hoặc đã đóng.");

            existing.TutorialId = tutorial.Id;
            existing.CreatedByUserId = command.ActorId;
            existing.IsAutoGenerated = false;
            existing.UpdatedAt = DateTime.UtcNow;
            await _challenges.UpdateAsync(existing, ct);
            challengeId = existing.Id;
        }

        var saved = await _challenges.GetByIdAsync(challengeId, ct)
            ?? throw new NotFoundException("Weekly challenge not found after save.");

        return saved.ToDto(submissionCount: 0, hasSubmittedThisWeek: null, myChallengeStreak: null);
    }

    private static DateOnly GetTodayGmt7() => DateOnly.FromDateTime(DateTime.UtcNow.AddHours(7));
}
