using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrigamiPlatform.Domain.Entities;

namespace OrigamiPlatform.Infrastructure.Persistence.Configurations;

public class DailyChallengeConfiguration : IEntityTypeConfiguration<DailyChallenge>
{
    public void Configure(EntityTypeBuilder<DailyChallenge> builder)
    {
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).ValueGeneratedNever();

        builder.Property(c => c.Status).HasConversion<string>().HasMaxLength(20).IsRequired();
        builder.Property(c => c.IsAutoGenerated).HasDefaultValue(false);

        // BR-34: only one challenge per calendar day
        builder.HasIndex(c => c.ChallengeDate).IsUnique();

        builder.HasOne(c => c.Tutorial)
               .WithMany()
               .HasForeignKey(c => c.TutorialId)
               .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(c => c.CreatedByUser)
               .WithMany()
               .HasForeignKey(c => c.CreatedByUserId)
               .OnDelete(DeleteBehavior.Restrict);

        builder.HasMany(c => c.Submissions)
               .WithOne(s => s.DailyChallenge)
               .HasForeignKey(s => s.DailyChallengeId)
               .OnDelete(DeleteBehavior.Cascade);
    }
}
