using Moq;
using OrigamiPlatform.Application.Commands.DailyChallenge;
using OrigamiPlatform.Application.Common;
using OrigamiPlatform.Application.Interfaces;
using OrigamiPlatform.Domain.Entities;
using OrigamiPlatform.Domain.Enums;
using Xunit;

namespace OrigamiPlatform.Tests.Commands.DailyChallenge;

public class ExplicitActivateDailyChallengeHandlerTests
{
    private readonly Mock<IDailyChallengeRepository> _challengesMock;
    private readonly Mock<IHatGapTransactionRepository> _hatGapTransactionsMock;
    private readonly Mock<IBadgeRepository> _badgesMock;
    private readonly Mock<IUserBadgeRepository> _userBadgesMock;
    private readonly Mock<INotificationService> _notificationsMock;
    private readonly HatGapAwardService _hatGapService;
    private readonly BadgeAwardService _badgeService;
    private readonly ActivateDailyChallengeHandler _handler;

    public ExplicitActivateDailyChallengeHandlerTests()
    {
        _challengesMock = new Mock<IDailyChallengeRepository>();
        
        _hatGapTransactionsMock = new Mock<IHatGapTransactionRepository>();
        _hatGapService = new HatGapAwardService(_hatGapTransactionsMock.Object);
        
        _badgesMock = new Mock<IBadgeRepository>();
        _userBadgesMock = new Mock<IUserBadgeRepository>();
        _notificationsMock = new Mock<INotificationService>();
        _badgeService = new BadgeAwardService(_badgesMock.Object, _userBadgesMock.Object, _notificationsMock.Object);
        
        _handler = new ActivateDailyChallengeHandler(
            _challengesMock.Object, 
            _hatGapService, 
            _badgeService, 
            _notificationsMock.Object);
    }

    [Fact]
    public async Task HandleAsync_AlreadyScheduledChallenge_UpdatesToActive()
    {
        // Arrange
        var command = new ActivateDailyChallengeCommand();
        var tutorial = new Tutorial { Id = Guid.NewGuid(), Title = "Origami Crane", AuthorId = Guid.NewGuid() };
        var challenge = new OrigamiPlatform.Domain.Entities.DailyChallenge 
        { 
            Id = Guid.NewGuid(), 
            Status = DailyChallengeStatus.Scheduled,
            Tutorial = tutorial 
        };

        _challengesMock
            .Setup(x => x.GetByDateAsync(It.IsAny<DateOnly>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(challenge);

        _hatGapTransactionsMock
            .Setup(x => x.GetLatestBalanceAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(0);
            
        // Act
        await _handler.HandleAsync(command);

        // Assert
        Assert.Equal(DailyChallengeStatus.Active, challenge.Status);
        _challengesMock.Verify(x => x.UpdateAsync(challenge, It.IsAny<CancellationToken>()), Times.Once);
        
        _notificationsMock.Verify(x => x.NotifyUserAsync(
            tutorial.AuthorId,
            NotificationType.TutorialSelectedAsChallenge,
            It.IsAny<string>(),
            nameof(OrigamiPlatform.Domain.Entities.DailyChallenge),
            challenge.Id,
            It.IsAny<CancellationToken>()), Times.Once);
    }
    
    [Fact]
    public async Task HandleAsync_NoChallengeToday_PicksTutorialAndCreatesChallenge()
    {
        // Arrange
        var command = new ActivateDailyChallengeCommand();
        
        _challengesMock
            .Setup(x => x.GetByDateAsync(It.IsAny<DateOnly>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((OrigamiPlatform.Domain.Entities.DailyChallenge)null);
            
        _challengesMock
            .Setup(x => x.GetRecentlyUsedTutorialIdsAsync(It.IsAny<DateOnly>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new HashSet<Guid>());

        var tutorial = new Tutorial { Id = Guid.NewGuid(), Title = "Origami Crane", AuthorId = Guid.NewGuid() };
        var candidates = new List<(Tutorial, int)> { (tutorial, 10) };
        
        _challengesMock
            .Setup(x => x.GetEligibleCandidatesAsync(It.IsAny<IReadOnlySet<Guid>>(), It.IsAny<TutorialDifficulty?>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(candidates);
            
        _hatGapTransactionsMock
            .Setup(x => x.GetLatestBalanceAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(0);

        // Act
        await _handler.HandleAsync(command);

        // Assert
        _challengesMock.Verify(x => x.AddAsync(It.Is<OrigamiPlatform.Domain.Entities.DailyChallenge>(c => 
            c.TutorialId == tutorial.Id && 
            c.Status == DailyChallengeStatus.Active &&
            c.IsAutoGenerated == true), It.IsAny<CancellationToken>()), Times.Once);
            
        _notificationsMock.Verify(x => x.NotifyUserAsync(
            tutorial.AuthorId,
            NotificationType.TutorialSelectedAsChallenge,
            It.IsAny<string>(),
            nameof(OrigamiPlatform.Domain.Entities.DailyChallenge),
            It.IsAny<Guid>(),
            It.IsAny<CancellationToken>()), Times.Once);
    }
}
